os: osx
language: swift
osx_image: xcode10.1

install:
- gem install xcpretty-travis-formatter

script:
- xcodebuild test -project ./Sketching.xcodeproj -scheme SketchingTests | xcpretty -f `xcpretty-travis-formatter`
